# Yang-gumi release: 1.3.0
[global]
developmentMode = false

[server]
port = 8501
headless = true
enableStaticServing = true
enableWebsocketCompression = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false
